### PR TITLE
Run buildifier over all BUILD syntax files excluding generated files.

### PR DESCRIPTION
**Pull request by nlewycky**

### CODE REVIEW

**Comment by oferb** [comment]
Hey,
There's a lot of code changes here that are not yours.
I know it's not your fault, but wondering how we can prevent these (and accidental merge errors).
@vmax Git expert - any ideas? :)

**Comment by vmax-reef** [comment]
@nlewycky would be best it you do `git reset --hard master` on your branch, re-run the `buildifier` and do `git push --force`

**Comment by vmax** [comment]
@nlewycky would be best it you do `git reset --hard master` on your branch, re-run the `buildifier` and do `git push --force`

**Comment by nlewycky** [comment]
Done. Please take a look!

**Comment by nlewycky** [comment]
Doh, thanks! Excluded third_party/maven as generated.

**Pull request merged**
