### PR TITLE
Add sha256 entries for all http_archive's.

### PR DESCRIPTION
**Pull request by nlewycky**

### CODE REVIEW

**Comment by nlewycky** [comment]
Er, I don't have a particularly good technique, I ran wget on the urls to download the files, ran sha256sum over them and pasted the results into the workspace file. Do you want that written down? If so, where?

**Comment by oferb** [comment]
If you can write that down in the WORKSPACE file, that'd be great. Thanks!!

**Comment by nlewycky** [comment]
Done?

**Comment by oferb** [comment]
Yup :)

**Pull request merged**
